<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose images_images</name>
   <tag></tag>
   <elementGuidId>8b3afdb4-f086-4585-948f-299f45ff0fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_3jqbps9r9 > div.modal-dialog.modal-xl > div.modal-content > div.modal-body > form > div.flex.flex-row.justify-center.gap-5.form-create > div.w-full.create-layout > div.mx-auto.cursor-pointer.relative.mt-5 > input[name=&quot;images&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='images'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>043930f1-103d-4947-b6f5-a42d56d3881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>82c45ad1-aa47-49a8-82c3-a91fd92a6ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>images</value>
      <webElementGuid>3c6d5cba-f755-4881-ba35-3d9d86ec4e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input w-full h-full top-0 left-0 absolute opacity-0 bg-yellow-300</value>
      <webElementGuid>a6552b07-5391-45de-bf52-48f98b901507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Attach files</value>
      <webElementGuid>f02bbd39-0407-48a8-8847-3f5219324bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>cac83d8b-beca-446c-869f-5e7859a704a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_3jqbps9r9&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;flex flex-row justify-center gap-5 form-create&quot;]/div[@class=&quot;w-full create-layout&quot;]/div[@class=&quot;mx-auto cursor-pointer relative mt-5&quot;]/input[@class=&quot;custom-file-input w-full h-full top-0 left-0 absolute opacity-0 bg-yellow-300&quot;]</value>
      <webElementGuid>6f8850b8-ada7-43c4-948a-15e7e490d8f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='images'])[2]</value>
      <webElementGuid>d072343d-9b42-4a5f-8be1-98b4e0304cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_3jqbps9r9']/div/div/div[2]/form/div[7]/div/div/input</value>
      <webElementGuid>36e03a5a-2782-40f0-9560-163a94064e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>ed2dd616-83c6-49a0-80f7-216369d87f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'images' and @placeholder = 'Attach files']</value>
      <webElementGuid>934deec9-cb63-456e-b1a5-6897dc02df0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
