<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Choose images_rounded-md</name>
   <tag></tag>
   <elementGuidId>c2c550da-d109-4baa-bece-f63f0a29de06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h-40.w-40.relative.image-fit.cursor-pointer.zoom-in.mx-auto > img.rounded-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_z4v2g6q0w']/div/div/div[2]/form/div[8]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32cb04ec-b09f-416d-b7c3-2e7ee484e0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:http://localhost:3000/be9dd844-bacb-4e5c-9a6a-0fb1fc59ff33</value>
      <webElementGuid>63a01cb8-a27c-4f07-a128-b4d2a28277b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>0736b9c2-6d16-48cf-ac24-3c243c044ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-md</value>
      <webElementGuid>7afe3d10-79eb-4987-b647-c9d15bf63d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_z4v2g6q0w&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;selected-images&quot;]/div[@class=&quot;image-preview&quot;]/div[@class=&quot;h-40 w-40 relative image-fit cursor-pointer zoom-in mx-auto&quot;]/img[@class=&quot;rounded-md&quot;]</value>
      <webElementGuid>4d426271-1ea0-4782-8e5b-44f5772481d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_z4v2g6q0w']/div/div/div[2]/form/div[8]/div/div/img</value>
      <webElementGuid>67b1ca94-5ca6-4e0a-ae3e-03f2fc3d0ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Preview']</value>
      <webElementGuid>29420aec-8351-4c60-9582-015d6dafcff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/img</value>
      <webElementGuid>8038af04-34e6-437f-8efe-98ef9909adfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'blob:http://localhost:3000/be9dd844-bacb-4e5c-9a6a-0fb1fc59ff33' and @alt = 'Preview']</value>
      <webElementGuid>5c8d38af-5268-404e-b53d-6c7e13322599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
