<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose images_images</name>
   <tag></tag>
   <elementGuidId>ed785e60-aa79-461b-86f8-2c0d0a9a59da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_3jqbps9r9 > div.modal-dialog.modal-xl > div.modal-content > div.modal-body > form > div.flex.flex-row.justify-center.gap-5.form-create > div.w-full.create-layout > div.mx-auto.cursor-pointer.relative.mt-5 > input[name=&quot;images&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='images'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28d7e0fe-fe39-43b6-a041-85d78804d0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>20618c81-fc51-4da3-82a2-2e487e1a980c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>images</value>
      <webElementGuid>39ee1a7d-f4f7-4fb2-b693-f992cdcbfb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input w-full h-full top-0 left-0 absolute opacity-0 bg-yellow-300</value>
      <webElementGuid>26afa6e5-2c52-4252-8a45-68c421333591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Attach files</value>
      <webElementGuid>4bca312b-932f-4b17-9082-3d9ff2ff8b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>83a09c53-370f-40b5-81b2-9137b1b2dc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_3jqbps9r9&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;flex flex-row justify-center gap-5 form-create&quot;]/div[@class=&quot;w-full create-layout&quot;]/div[@class=&quot;mx-auto cursor-pointer relative mt-5&quot;]/input[@class=&quot;custom-file-input w-full h-full top-0 left-0 absolute opacity-0 bg-yellow-300&quot;]</value>
      <webElementGuid>95670a11-8c98-49b2-98ce-000049458688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='images'])[2]</value>
      <webElementGuid>941ee705-7f49-4cb3-b76d-11a930d3125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_3jqbps9r9']/div/div/div[2]/form/div[7]/div/div/input</value>
      <webElementGuid>66744d12-969a-454c-b1bd-3947809ca03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>278d02bd-ca16-412f-b809-a77ee61627ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'images' and @placeholder = 'Attach files']</value>
      <webElementGuid>3afa9350-cc64-4c64-8588-547aa5a6a21d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
