<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select the categoryChopstickR_0b38fe</name>
   <tag></tag>
   <elementGuidId>e080e967-4656-4d02-b70a-fb23eb3e7211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_o18ot8szd > div.modal-dialog.modal-xl > div.modal-content > div.modal-body > form > div.flex.flex-row.justify-center.gap-5.form-create > div.w-full.create-layout > select[name=&quot;category&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@name='category'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5335640-7116-4a74-bb92-6c2daf0603fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pr-10</value>
      <webElementGuid>57a1f14c-dddf-42cf-9f78-aa9450474be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter category</value>
      <webElementGuid>ec400602-38f1-4781-80b6-e321454729c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>d7254cfc-97e3-4943-a722-fc2d0fa932ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select the categoryChopstickROSEFlowerBowlsSpoon spoonTraditional lifeTREE</value>
      <webElementGuid>02ef00d8-9c49-4179-bc0e-8892accec4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_o18ot8szd&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;flex flex-row justify-center gap-5 form-create&quot;]/div[@class=&quot;w-full create-layout&quot;]/select[@class=&quot;form-control pr-10&quot;]</value>
      <webElementGuid>27994820-7ea2-45b4-92be-943ecdac112a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='category'])[2]</value>
      <webElementGuid>d4e9d0b4-816d-4358-9970-bddb89513c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_o18ot8szd']/div/div/div[2]/form/div/div/select</value>
      <webElementGuid>8f2e2b3a-d376-49b8-8b9c-9c619db36706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>d3cc087f-0cab-4454-bbc5-ac86f7835883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/preceding::select[1]</value>
      <webElementGuid>28267ee0-c0ed-4501-b6ac-4f27980c1781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div/div/select</value>
      <webElementGuid>4fb6cfc0-2df2-44c2-a02c-482058a818c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Enter category' and @name = 'category' and (text() = 'Please select the categoryChopstickROSEFlowerBowlsSpoon spoonTraditional lifeTREE' or . = 'Please select the categoryChopstickROSEFlowerBowlsSpoon spoonTraditional lifeTREE')]</value>
      <webElementGuid>66da0925-bcdf-4cbf-882a-cb966b5371b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
