<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Oke</name>
   <tag></tag>
   <elementGuidId>05ac17eb-ab26-4f2a-9bb8-a54aace234bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='Oke']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.intro-x.mx-auto.text-center.flex.justify-center > button.btn.btn-primary.w-24.mb-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6520acd-8d6e-4704-8aec-7ae8659b0d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-24 mb-2</value>
      <webElementGuid>be6afe5f-3dd8-4059-8479-059a0be55384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oke</value>
      <webElementGuid>a30a3f7c-5e77-45de-afed-ed8bd7d0b477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_h0na3t1ur&quot;)/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/div[@class=&quot;intro-x mx-auto text-center flex justify-center&quot;]/button[@class=&quot;btn btn-primary w-24 mb-2&quot;]</value>
      <webElementGuid>87d3f7cb-bd32-43dd-a87f-232fb2a900b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_h0na3t1ur']/div/div/div[3]/div/button</value>
      <webElementGuid>7dec49b8-ae63-48b3-a666-c2c355f9be82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>eb5e5e1c-6d82-4752-bc16-8f0227502ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>2246f9a8-9cf2-4e6e-892a-eb0df2625faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oke']/parent::*</value>
      <webElementGuid>6804e8eb-c1e0-4a2e-9263-5754d8c089fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>6b43a955-2116-4b32-b315-8c5ea201f87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Oke' or . = 'Oke')]</value>
      <webElementGuid>438d9a03-bc52-4588-93bf-167a693b2a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
